import {
    SiVisualstudiocode,
    SiSublimetext,
    SiMicrosoftedge,
    SiGooglechrome,
    SiVercel,
    SiPrettier,
    SiPnpm,
    SiYarn,
    SiFigma,
    SiInsomnia,
    SiSpotify,
    SiGrammarly,
    SiGooglekeep,
    SiNotepadplusplus,
    SiPostman,
    SiWindows,
    SiGit,
    SiGithub,
    SiFirefoxbrowser,
    SiUbuntu,
    SiAdobephotoshop,
    SiAnydesk,
    SiSourcetree,
    SiXampp,
    SiVlcmediaplayer,
    SiVmware,
    SiSimplenote,
} from 'react-icons/si';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
    system: {
        title: 'System',
        data: [
            {
                name: 'VSCode',
                description: 'Primary Code editor',
                icon: SiVisualstudiocode,
                link: 'https://code.visualstudio.com/download',
            },
            {
                name: 'Sublime Text',
                description: 'Text editor',
                icon: SiSublimetext,
                link: 'https://www.techspot.com/downloads/5546-sublime-text.html',
            },
            {
                name: 'Windows 10',
                description: 'Operating System',
                icon: SiWindows,
                link: 'https://www.microsoft.com/software-download/windows10',
            },
            {
                name: 'Ubuntu',
                description: 'Operating System',
                icon: SiUbuntu,
                link: 'https://ubuntu.com/download/desktop',
            },
            {
                name: 'Chrome',
                description: 'Primary Browser',
                icon: SiGooglechrome,
                link: 'https://www.google.com/chrome',
            },
            {
                name: 'FireFox',
                description: 'Secondary Browser',
                icon: SiFirefoxbrowser,
                link: 'https://www.mozilla.org/en-US/firefox/new/',
            },
            {
                name: 'Microsoft Edge',
                description: 'Third Browser',
                icon: SiMicrosoftedge,
                link: 'https://www.microsoft.com/en-us/edge',
            },
        ],
    },
    software: {
        title: 'Software & Applications',
        data: [
            {
                name: 'Vercel',
                description: 'Hosting for Projects',
                icon: SiVercel,
                link: 'http://vercel.com/',
            },
            {
                name: 'Prettier',
                description: 'For Code formatting',
                icon: SiPrettier,
                link: 'https://prettier.io/',
            },
            {
                name: 'Git',
                description: 'Version Control',
                icon: SiGit,
                link: 'https://git-scm.com/downloads',
            },
            {
                name: 'Github Desktop',
                description: 'To Manage the Github Project and Changes',
                icon: SiGithub,
                link: 'https://desktop.github.com/',
            },
            {
                name: 'Figma',
                description: 'Primary Design tool',
                icon: SiFigma,
                link: 'https://www.figma.com/downloads/',
            },
            {
                name: 'AnyDesk',
                description: 'Remote Desktop Software',
                icon: SiAnydesk,
                link: 'https://anydesk.com/en/downloads/windows',
            },
            {
                name: 'Photoshop',
                description: 'Photo 7 Design Software',
                icon: SiAdobephotoshop,
                link: 'https://www.adobe.com/products/photoshop/free-trial-download.html',
            },
            {
                name: 'Yarn',
                description: 'Alternative Package Manager',
                icon: SiYarn,
                link: 'https://classic.yarnpkg.com/lang/en/docs/install/',
            },
            {
                name: 'Insomnia',
                description: 'For testing APIs',
                icon: SiInsomnia,
                link: 'https://insomnia.rest/download',
            },
            {
                name: 'Spotify',
                description: 'To Listen Music',
                icon: SiSpotify,
                link: 'https://www.spotify.com/us/download/windows/',
            },
            {
                name: 'Grammarly',
                description: 'Typing assistant that reviews spelling, grammar, etc.',
                icon: SiGrammarly,
                link: 'https://www.grammarly.com/',
            },
            {
                name: 'Simplenote',
                description: 'Quick Note',
                icon: SiSimplenote,
                link: 'https://simplenote.com/',
            },
            {
                name: 'Notepad++',
                description: 'Quick Code Editing',
                icon: SiNotepadplusplus,
                link: 'https://keep.google.com/',
            },
            {
                name: 'Postman',
                description: 'API Testing',
                icon: SiPostman,
                link: 'https://postman.com',
            },
            {
                name: 'SourceTree',
                description: 'A free Git client for Windows and Mac',
                icon: SiSourcetree,
                link: 'https://www.sourcetreeapp.com/',
            },
            {
                name: 'XAMPP',
                description: 'Apache distribution containing MariaDB, PHP, and Perl',
                icon: SiXampp,
                link: 'https://www.apachefriends.org/download.html',
            },
            {
                name: 'VLC Player',
                description: 'Cross-platform multimedia player',
                icon: SiVlcmediaplayer,
                link: 'https://www.videolan.org/vlc/download-windows.en.html',
            },
            {
                name: 'VMware',
                description: 'Virtual machines on Linux or Windows PCs',
                icon: SiVmware,
                link: 'https://www.vmware.com/products/workstation-pro/workstation-pro-evaluation.html',
            },
        ],
    },
};
